### ISSUE TITLE
libs3 version?

### ISSUE THREAD

**Issue by gijzelaerr** [UCBerkeleySETI/gbt_seti#2]
Ubuntu 18.04 comes with libs3 2.0-3, but when compiled against this version I run into troubles:
```
s3util.c: In function ‘responsePropertiesCallback’:
s3util.c:284:19: error: ‘S3ResponseProperties {aka const struct S3ResponseProperties}’ has no member named ‘usesServerSideEncryption’
     if (properties->usesServerSideEncryption) {
                   ^~
<builtin>: recipe for target 's3util.o' failed
make: *** [s3util.o] Error 1
```

Currently, the Dockerfile builds against the latest master. Is this absolutely required? If so, we should probably make a new release for libs3. Problem is that it looks like the author of libs3 doesn't like releases also.

**Comment by gijzelaerr** [comment]
The current master doesn't build on Ubuntu 18.04:

https://github.com/bji/libs3/issues/75

**Comment by gijzelaerr** [comment]
there are more compatiblity issues:
```
filterbankutil.c:1229:9: error: too many arguments to function ‘S3_put_object’
         S3_put_object(&bucketContext, fitsname, fitslen, &putProperties, 0,
         ^~~~~~~~~~~~~
In file included from filterbankutil.c:2:0:
/usr/include/libs3.h:1616:6: note: declared here
 void S3_put_object(const S3BucketContext *bucketContext, const char *key,
      ^~~~~~~~~~~~~
filterbankutil.c:1262:9: error: too many arguments to function ‘S3_put_object’
         S3_put_object(&bucketContext, fitsname, fitslen, &putProperties, 0,
         ^~~~~~~~~~~~~
In file included from filterbankutil.c:2:0:
/usr/include/libs3.h:1616:6: note: declared here
 void S3_put_object(const S3BucketContext *bucketContext, const char *key,
      ^~~~~~~~~~~~~
```

**Comment by gijzelaerr** [comment]
So the differences between the latest release (2.0) and current master are:

* in master `S3_put_object` has a new timeout argument.

**Comment by gijzelaerr** [comment]
fixed in https://github.com/UCBerkeleySETI/gbt_seti/pull/3
